learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
# from learning_logs_app import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('',include('learning_logs_app.urls')),
    # path('', views.index,name='index'),
    # path('topics/',views.topics,name='topics'),
    # path('topics/<int:topic_id>/',views.topic,name='topic'),
    
    # #page for adding a new topic
    # path('new_topic/',views.new_topic,name='new_topic'),

    # #page for adding a new entry
    # path('new_entry/<int:topic_id>',views.new_entry,name='new_entry'),

    # #page for editing an existing entry
    # path('edit_entry/<int:entry_id>',views.edit_entry,name='edit_entry'),


]

learning_logs_app/urls.py
''' Defines URL patterns for learning_logs_app'''

from django.urls import path
from learning_logs_app import views


app_name='learning_logs_app'
urlpatterns=[

    path('', views.index,name='index'),
    path('topics/',views.topics,name='topics'),
    path('topics/<int:topic_id>/',views.topic,name='topic'),
    
    #page for adding a new topic
    path('new_topic/',views.new_topic,name='new_topic'),

    #page for adding a new entry
    path('new_entry/<int:topic_id>',views.new_entry,name='new_entry'),

    #page for editing an existing entry
    path('edit_entry/<int:entry_id>',views.edit_entry,name='edit_entry'),
]

users/urls.py
'''Defines URL patterns for users_app'''

from django.urls import path
from django.contrib.auth.views import LoginView


from users import views

app_name='users'

urlpatterns = [
    #login page

    path('login/',LoginView.as_view(),name='login'),
    # path('login/',views.loign,name='login')
    #Logout page. 

    path('logout/',views.logout_view,name='logout'),

    #Registration Page
    path('register/',views.register,name='register'),


]

learning_logs_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    ''' A topic the user is learning about''' 
    text= models.CharField(max_length=200)
    date_added=models.DateTimeField(auto_now_add=True)
    owner=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        ''' Return a sstring representation of the model. ''' 
        return self.text


class Entry(models.Model):
    ''' Something specifc learned about a topic''' 
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural= 'entries'

    def __str__(self):
        ''' Return a string representation of the model. '''
        return self.text[:50] +'...'
        

users/models.py
from django.db import models

# Create your models here.

learning_logs_app/forms.py
from django import forms 
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model= Topic
        fields=['text']
        labels={'text':''}

class EntryForm(forms.ModelForm):

    class Meta:
        model= Entry
        fields=['text']
        labels={'text':''}
        widgets={'text':forms.Textarea(attrs={'cols':80})}
        

learning_logs_app/views.py
from django.shortcuts import render
from .models import Topic,Entry
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    ''' The home page for learning log ''' 
    return render(request,'learning_logs_template/index.html')

@login_required
def topics(request):
    ''' Show all topics''' 
    topics=Topic.objects.filter(owner=request.user).order_by('date_added')
    context={
        'topics':topics
        }
    return render(request,'learning_logs_template/topics.html',context)

@login_required
def topic(request,topic_id):
    ''' Show a sngle topic and all its entries.''' 
    topic=Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    entries=topic.entry_set.order_by('-date_added')
    context={
        'topic':topic,
        'entries':entries
    }

    return render(request,'learning_logs_template/topic.html',context)

@login_required
def new_topic(request):
    ''' Add a new topic'''
    if request.method!='POST':
        #No Data submitted; create a blank form 
        form= TopicForm()

    else:
        #POST data submitted; process data. 
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner=request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs_app:topics'))

    context={
        'form':form

    }

    return render(request,'learning_logs_template/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    ''' Add a new entry for a particular topic. ''' 
    topic=Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        #No data submitted; create a blank form. 
        form=EntryForm()
    else:
        #POST data submitted; process data. 
        form=EntryForm(data=request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs_app:topic',args=[topic_id]))

    context={
    'topic':topic,
    'form':form
    }
    return render(request,'learning_logs_template/new_entry.html',context)
        

@login_required    
def edit_entry(request,entry_id):
    ''' Edit an existing entry'''
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic

    if topic.owner !=request.user:
        raise Http404

    if request.method!='POST':
        #initial request;pre-fill form with the current entry. 
        form=EntryForm(instance=entry)

    else:
        #POST data submitted; process data
        form=EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs_app:topic',args=[topic.id]))

    context={
        'entry':entry,
        'topic':topic,
        'form':form
    }

    return render(request,'learning_logs_template/edit_entry.html',context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    ''' Log the user out ''' 
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs_app:index'))

def register(request):
    ''' Register a new user ''' 
    if request.method !='POST':
        #Display blank registrartion form 
        form=UserCreationForm()

    else: 
        form=UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user= form.save()
            #Log the user in and then redirect to home page 
            authenticated_user=authenticate(username=new_user.username, password=request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs_app:index'))

    context={
        'form':form
    }

    return render(request,'users/register.html',context)

learning_logs_app/templates/learning_logs_template/base.html
{%load bootstrap3%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Learning Log</title>

    {%bootstrap_css%}
    {%bootstrap_javascript%}

</head>

<body>
    <!-- Static Navbar -->

    <nav class='navbar navbar=default navbar-static-top'>

        <div class='container'>

            <div class='navbar-header'>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{%url 'learning_logs_app:index'%}">Learning Log</a>
            </div>

            <div id='navbar' class='navbar-collapse collapse'>
                <ul class="nav navbar-nav">
                    <li> <a href="{%url 'learning_logs_app:topics'%}">Topics</a> </li>

                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {%if user.is_authenticated%}
                    <li><a> Hello,{{user.username}}.</a></li>
                    <li> <a href="{%url 'users:logout'%}">Log out</a></li>
                    {%else%}
                    <li> <a href="{%url 'users:register'%}">Register</a>
                    </li>
                    <li> <a href="{%url 'users:login'%}">Log in</a>
                    </li>
                    {%endif%}

                </ul>
            </div>
            <!-- /.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <div class="page-header">
            {%block header%}{%endblock header%}
        </div>

        <div>
            {%block content%}{%endblock content%}

        </div>
    </div>
    <!-- /Container -->


</body>

</html>

learning_logs_app/templates/learning_logs_template/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit Entry</title>
</head>
<body>
    {%extends 'learning_logs_template/base.html'%}

    {%block content%}
    <p><a href="{%url 'learning_logs_app:topic' topic.id%}">{{topic}}</a></p>

    <p>Edit Entry</p>
    <form action="{%url 'learning_logs_app:edit_entry' entry.id%}" method="post">
        {%csrf_token%}
        {{form.as_p}}

        <button type="submit">Save Changes</button>

    </form>

    {%endblock content%}
</body>
</html>

learning_logs_app/templates/learning_logs_template/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
</head>

<body>

    {%extends "learning_logs_template/base.html"%}

    {%block header%}
    <div class="jumbotron">
        <h2>Track your learning.</h2>
    </div>
    {%endblock header%}




    {%block content%}
    <h3>
        <a href="{%url 'users:register'%}">Register an account</a> to make
        your own Learning Log, and list the topics you're learning about.

    </h3>

    <h3>
        Whenever you learn something new about a topic, mae an entry summarizing what you've learned
    </h3>
    {%endblock content%}


</body>

</html>

learning_logs_app/templates/learning_logs_template/new_entry.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Entry</title>
</head>

<body>
    {%extends 'learning_logs_template/base.html'%}

    {%block content%}
    <p><a href="{%url 'learning_logs_app:topic' topic.id%}">{{topic}}</a></p>

    <p>Add a new entry</p>
    <form action="{%url 'learning_logs_app:new_entry' topic.id%}" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Add Entry</button>

    </form>
    {%endblock content%}
</body>
</html>

learning_logs_app/templates/learning_logs_template/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Topic</title>
</head>
<body>
    {%extends "learning_logs_template/base.html"%}

    {%block content%}

    <p>Add a new topic:</p>
    <form action="{%url 'learning_logs_app:new_topic'%}" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Add Topic</button>
    </form>
    {%endblock content%}


</body>
</html>

learning_logs_app/templates/learning_logs_template/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Topic</title>
</head>
<body>
    {%extends "learning_logs_template/base.html"%}

    {%block header%}
    <h2>Topic</h2>
    {%endblock header%}

    {%block content%}
    <p>Topic: {{topic}}</p>

    <p>Entries: </p>
    <p>
        <a href="{%url 'learning_logs_app:new_entry' topic.id%}">add new entry</a>
    </p>
    
        {%for entry in entries%}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                        {{entry.date_added|date:'M d,Y H:i'}}

                        <small>
                                <a href="{%url 'learning_logs_app:edit_entry' entry.id%}">Edit Entry</a>
                        </small>

                </h3>

            </div>
<div class="panel-body">
        {{entry.text|linebreaks}}
</div>
        </div>
   

        {%empty%}
        
            The are no entries for this topic yet.
        
        {%endfor%}
    

    {%endblock content%}
</body>
</html>

learning_logs_app/templates/learning_logs_template/topics.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Topics</title>
</head>

<body>
    {%extends 'learning_logs_template/base.html'%}

    {%block header%}
    <h2>Topics</h2>
    {%endblock header%}


    {%block content%}
    <p>Topics:</p>
    <ul>
        {%for topic in topics%}

        <h3>
            <a href="{%url 'learning_logs_app:topic' topic.id%}">{{topic}}</a>
        </h3>
        {%empty%}
        <li>
            No topics have been added yet
        </li>
        {%endfor%}
    </ul>

    <h3>
        <a href="{%url 'learning_logs_app:new_topic'%}">Add a new topic</a>
    </h3>

    {%endblock content%}
</body>

</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Regestration</title>
</head>
<body>
    {%extends 'learning_logs_template/base.html'%}

    {%block content%}
    <form action="{%url 'users:register'%}" method="post">
        {%csrf_token%}
        {{form.as_p}}

        <button type="submit">Register</button>
        <input type="hidden" name="next" value="{%url 'learning_logs_app:index'%}">
    </form>
    {%endblock content%}
</body>
</html>